spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nimerce1234@gmail.com
spring.mail.password=sdtc xrts pqne ezbf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.mime.charset=UTF-8
spring.mail.properties.mail.smtp.localhost=localhost
spring.mail.properties.mail.mime.language=es

# TWILIO SMS
twilio.sid=XXXX
twilio.token=XXXX
twilio.phone=+51999999999

# WHATSAPP
whatsapp.token=XXXX
whatsapp.phone=+51999999999